name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        example:
          - "examples/mbed-rtos-blink-baremetal"
          - "examples/mbed-rtos-usb-msd"
          - "examples/mbed-rtos-ethernet-tls"
          - "examples/mbed-rtos-kvstore"
          - "examples/mbed-rtos-psa"
          - "examples/mbed-legacy-examples/mbed-events"
          - "examples/mbed-legacy-examples/mbed-rtos-tls-client"
          - "examples/zephyr-blink"
          - "examples/zephyr-net-telnet"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
